
decision_tree:
  criterion: ['gini', 'entropy', 'log_loss']
  splitter: ['best', 'random']
  min_samples_split: [3,5,7,10,15]
  min_samples_leaf: [2,5,10]
random_forest:
  max_depth: [25, 50, 75, 100]
  criterion: ['gini', 'entropy']  
  max_features: ['sqrt', 'log2', 'None']
  min_samples_leaf: [2,5,10]
  min_samples_split: [2,5,10]
  n_estimators: [50,100,150,200]
  # random_forest:
  # max_depth: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
  # criterion: ['gini', 'entropy']  
  # max_features: [0.3,0.5,0.7,0.9]
  # min_samples_leaf: [3,5,7,10,15]
  # min_samples_split: [2,5,10]
  # n_estimators: [50,100,200,400,600]
svc:
  C: [0.1, 1, 10, 100]
  kernel: [linear, 'rbf', 'poly']
  gamma: ['scale', 'auto']
  degree: [1, 2, 3]
    #  cache_size: 4096
