
decision_tree:
  criterion: ['gini', 'entropy', 'log_loss']
  splitter: ['best', 'random']
  min_samples_split: [3,5,7,10,15]
  min_samples_leaf: [2,5,10]
random_forest:
  max_depth: [25, 50, 75, 100]
  criterion: ['gini', 'entropy']  
  max_features: ['sqrt', 'log2', NULL]
  min_samples_leaf: [2,5,10]
  min_samples_split: [2,5,10]
  n_estimators: [50,100,150,200]
svc:
  C: [0.1, 1, 10, 100]
  kernel: [linear, 'rbf', 'poly']
  gamma: ['scale', 'auto']
  degree: [1, 2, 3]
    #  cache_size: 4096
